### ISSUE TITLE
Full source code of DLLs

### ISSUE THREAD

**Issue by ask2018** [Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK#13]
@Blaukovitch could you please provide full source code of your kernel64, user64, Xfplat and other dlls? So we can compile and experiment with changes and try to use it with different software? I know you provided some examples in the other topic, but I mean something for total beginners, where we can just open it in Visual Studio, try to compile and slowly learn how to modify it.

**Comment by Vort** [comment]
There is additional reason to see source code: to check if patch adds more bugs.

**Comment by Blaukovitch** [comment]
Guys, i am updated [API-MS-WIN_XP](/Blaukovitch/API-MS-WIN_XP) repository (kerne64, user64, ...). 

The code of libraries is very simple, clear and primitive, without unnecessary C++ constructs (stl,vectored...). Most of them are stubs for WinAPI functions. For example, **API-MS-WIN-CORE-WINRT...** doesn't need to be written at all, because **AppX** (Microsoft Windows Store) is simply absent in Widnows 7. Naturally, returning an error for WINRT is even somewhat positive for the browser, since a huge amount of code will not be executed to interact with **AppX**.
**API-MS-WIN-CORE-LIBRARYLOADER-L1-2-0** is just a refs to **kernel32.dll** (need lib name for PE COFF import table only).

Must functionally: **kernel64.dll / user.64.dll / API-MS-WIN-SHCORE-SCALING-L1-1-1.dll**  

Would like to expand on the functionality of the missing components of **DirectX** 11/12 - as ref **(X)Mfplat.dll**


**(b)xcryptprimitives.dll** - detected as `anti-Windows 7` trick from Google Inc.

**Comment by ask2018** [comment]
Great and thank you. There is much more people who like to extend support for Windows 7, but most of us don't have enough skills to do it on our [own](https://github.com/jpsdr/MKVToolnix-QT5-Windows-7/issues/2).That means we need such examples and tutorials as you provided here to learn new stuff.
