### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by darkalexis1990** [Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK#4]
hello

thank you very much for this project

any thoughts for supporting also Edge??

OS: Win 7 latest build ( using bypasstoolv12)

thanks!

**Comment by Blaukovitch** [comment]
Hello!
Unlike other Chromium-based browsers, EDGE request [part of the DirectX API 12](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-d3d12serializeversionedrootsignature) and a new **MFSENSORGROUP.DLL** dynamic link library.
I don't have time to make such features in the near future yet. But otherwise the procedure is similar to changing binary code in Opera browser #2

**Comment by darkalexis1990** [comment]
thank you for your answer. can i ask somethine else here? is it possibly to patch Spotift latest version to work on 7? cause spotify bases on chromium. thanks!

**Comment by Blaukovitch** [comment]
"Is it possible to patch the latest version of Spotift to work on 7? Because Spotify works on chrome. It would be really cool to patch it."
Yes, it is possible. But not this time - the "Spotify.exe" import table contains many other _API-MS-. dlls_. It takes more time to write new libs for the import table. Sorry!

**Comment by ask2018** [comment]
@darkalexis1990 For Spotify maybe try this alternative client. It doesn't use electron. I don't use Spotify, so didn't try it. But according to description on some websites it should work on 7.
https://github.com/KRTirtho/spotube

**Comment by darkalexis1990** [comment]
> @darkalexis1990 For Spotify maybe try this alternative client. It doesn't use electron. I don't use Spotify, so didn't try it. But according to description on some websites it should work on 7. https://github.com/KRTirtho/spotube

It does not work i've checked it.

**Comment by darkalexis1990** [comment]
@Blaukovitch can you patch Spotify for 7 ESU thanks! :)

**Comment by darkalexis1990** [comment]
@Blaukovitch when you have time,please patch Edge also thanks a lot youre the best!!!

**Comment by Blaukovitch** [comment]
@darkalexis1990, **THX FOR YOU!**
At the moment I'm trying to finally solve the issue with a working sandbox in all versions of Chrome, starting with the current version **120.0.6099.71**. If it really works stably, I can think about how to make Microsoft Edge and other chromium-based projects work well, too, of course.

**Comment by Blaukovitch** [comment]
@darkalexis1990 
this screen in **draft version** EDGE for Windows 7 - unfortunately, due to the huge number of required improvements, it will not be released in the near future. But in general I can say that running the current version of **Microsoft EDGE** browser in **Windows 7** is as realistic as Google Chrome:
![image](https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/assets/116763547/d3bf3ccc-c3ae-4c0a-9c67-a52731d82cf9)

**Comment by darkalexis1990** [comment]
@Blaukovitch is there a guide to patch and use this draft version of edge???
also i saw in your video on youtube that you have installed some version of office 365? you patched above the 2002 version of 365? thanks!...

**Comment by Blaukovitch** [comment]
@darkalexis1990 
RELEASED stable **120.0.2210.77**  (but need still some fixes) version of **Microsoft EDGE** on separately branch:
https://github.com/Blaukovitch/Microsoft-EDGE-Windows-7-CRACK
![image](https://github.com/Blaukovitch/Microsoft-EDGE-Windows-7-CRACK/assets/116763547/68ce028b-ca4d-43a1-b237-afce83afb580)

**Comment by darkalexis1990** [comment]
@Blaukovitch YOU ARE A LIFE SAVIOR!!! 

what about the office i asked you? :)

**Comment by Blaukovitch** [comment]
@darkalexis1990, "office" - this is more difficulty theme ^)

**Comment by darkalexis1990** [comment]
hi didnt understand.did you patched the office 365????
